INSERT INTO smdcal.bureliai (burelis)
VALUES ("Šeimos medicinos būrelis"),
    ("Psichiatrijos būrelis"),
    ("Vidaus ligų būrelis"),
    ("Akušerijos ir ginekologijos būrelis"),
    ("Anesteziologijos būrelis"),
    ("Kardiologijos būrelis"),
    ("Vaikų ligų būrelis"),
    ("Radiologijos būrelis"),
    ("Intensyviosios terapijos būrelis"),
    ("Neurologijos būrelis"),
    ("Skubiosios medicinos būrelis"),
    ("Abdominalinės chirurgijos būrelis"),
    ("Odos ir venerinių ligų būrelis"),
    ("Endokrinologijos būrelis"),
    (
        "Plastinės ir rekonstrukcinės chirurgijos būrelis"
    ),
    (
        "Hematologijos, onkologijos ir transfuziologijos būrelis"
    ),
    ("Gastroenterologijos būrelis"),
    ("Akių ligų būrelis"),
    ("Ortopedijos – traumatologijos būrelis"),
    ("Pulmonologijos būrelis"),
    ("Teismo medicinos būrelis"),
    ("Neonatologijos būrelis"),
    ("Ausų, nosies ir gerklės ligų būrelis"),
    ("Širdies - krūtinės chirurgijos būrelis"),
    ("Imunologijos ir alergologijos būrelis"),
    ("Anatomijos būrelis"),
    ("Veido ir žandikaulių chirurgijos būrelis"),
    ("Kraujagyslių chirurgijos būrelis"),
    ("Neurochirurgijos būrelis"),
    ("Vaikų chirurgijos būrelis"),
    ("Reabilitacijos būrelis"),
    ("Chirurgijos pagrindų mokykla"),
    ("Vaikų ir paauglių psichiatrijos būrelis"),
    ("Urologijos būrelis"),
    ("Medicinos mokslų mokykla"),
    ("Kineziterapijos būrelis"),
    ("Klinikinės farmakologijos būrelis"),
    ("Maisto mokslo būrelis"),
    ("Dailės terapijos būrelis"),
    ("Veterinarinės medicinos būrelis"),
    ("Sveikatos psichologijos būrelis"),
    ("Gyvūnų mokslo būrelis"),
    ("Ergoterapijos būrelis"),
    (
        "Hematologijos, onkologijos ir transfuziologijos būrelis"
    ),
    ("Ortopedijos – traumatologijos būrelis"),
    ("Gastroenterologijos būrelis"),
    ("Imunologijos ir alergologijos būrelis"),
    ("Dailės terapijos būrelis"),
    ("Vaikų ir paauglių psichiatrijos būrelis"),
    ("Gyvūnų mokslo būrelis");